# Конфігурація WhatsApp Bridge
# Автор: Matrix Setup Team

homeserver:
  address: http://dendrite:8008
  domain: ${MATRIX_SERVER_NAME}

appservice:
  address: http://whatsapp-bridge:29329
  hostname: 0.0.0.0
  port: 29329
  database: sqlite:///whatsapp.db

bridge:
  username_format: whatsapp_{userid}
  displayname_template: "WhatsApp: {displayname}"
  avatar_template: "mxc://example.com/whatsapp_{userid}"

  permissions:
    ${MATRIX_SERVER_NAME}:
      - "@admin:${MATRIX_SERVER_NAME}"

  relay:
    enabled: false

  encryption:
    allow: false
    default: false

  delivery_receipts: false
  message_status_events: false
  message_error_notices: false

whatsapp:
  os_name: "Matrix WhatsApp Bridge"
  browser_name: "Chrome"
  version: "2.23.4.78"

logging:
  level: info
  timestamp: true 