# Конфігурація Matrix Dendrite сервера
version: 2

global:
  server_name: matrix.4ip.pp.ua
  private_key: /etc/matrix/dendrite/matrix_key.pem
  trusted_third_party_id_servers:
    - matrix.org
    - vector.im
  disable_federation: false
  presence:
    enable_inbound: false
    enable_outbound: false
  report_stats:
    enabled: false
  server_notices:
    enabled: false
  metrics:
    enabled: false
  dns_cache:
    enabled: false
  database:
    connection_string: postgresql://${POSTGRES_USER:-dendrite}:${POSTGRES_PASSWORD}@${POSTGRES_HOST:-postgres}:${POSTGRES_PORT:-5432}/${POSTGRES_DB:-dendrite}?sslmode=disable
    max_open_conns: 90
    max_idle_conns: 5
    conn_max_lifetime: -1
  cache:
    max_size_estimated: 1gb
    max_age: 1h

client_api:
  registration_disabled: false
  registration_shared_secret: ${REGISTRATION_SHARED_SECRET}
  guests_disabled: true
  enable_registration_captcha: false
  rate_limiting:
    enabled: true
    threshold: 20
    cooloff_ms: 500

federation_api:
  send_max_retries: 16
  disable_tls_validation: false
  disable_http_keepalives: false
  prefer_direct_fetch: false

media_api:
  base_path: /var/lib/matrix/media
  max_file_size_bytes: 10485760
  dynamic_thumbnails: false
  max_thumbnail_generators: 10
  thumbnail_sizes:
    - width: 32
      height: 32
      method: crop
    - width: 96
      height: 96
      method: crop
    - width: 640
      height: 480
      method: scale

sync_api:
  search:
    enabled: false
    index_path: "./searchindex"
    language: "en"

user_api:
  bcrypt_cost: 10
  auto_join_rooms: []

mscs:
  mscs: []

logging:
  - type: std
    level: info
