# Конфігурація Signal Bridge
# Автор: Matrix Setup Team

homeserver:
  address: http://dendrite:8008
  domain: ${MATRIX_SERVER_NAME}

appservice:
  address: http://signal-bridge:29328
  hostname: 0.0.0.0
  port: 29328
  database: sqlite:///signal.db

bridge:
  username_format: signal_{userid}
  displayname_template: "Signal: {displayname}"
  avatar_template: "mxc://example.com/signal_{userid}"

  permissions:
    ${MATRIX_SERVER_NAME}:
      - "@admin:${MATRIX_SERVER_NAME}"

  relay:
    enabled: false

  encryption:
    allow: false
    default: false

  delivery_receipts: false
  message_status_events: false
  message_error_notices: false

logging:
  level: info
  timestamp: true 